notifications:
  email:
    on_success: never
    on_failure: always

sudo: required

services:
  - docker

language: go
go:
  - "1.10"

install:
  - go get -u github.com/golang/dep/cmd/dep
  - cd function && dep ensure && cd ..
  - curl -sSL https://cli.openfaas.com | sudo sh

script:
 - bash script/coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash script/Dockerbuild.sh

deploy:
  provider: script
  script: bash script/Dockerpush.sh
  on:
    branch: master    